# 归一化
将一列数据变化到某个固定区间(范围)中，通常，这个区间是[0, 1] 或者（-1,1）之间的小数。主要是为了数据处理方便提出来的，把数据映射到0～1范围之内处理，更加便捷快速。



In [2]:
import numpy as np
import matplotlib.pyplot as plt

x = np.arange(1,11,1)
y = np.arange(0,1,0.1)
print(x.shape, y.shape)
plt.rcParams['axes.facecolor']='Black'


plt.scatter(x, y, c='b')

(10,) (10,)


In [3]:
margins = np.arange(10).reshape(-1,1)
print(margins.shape)
print(margins)
print(np.sum(margins))
margins[1] = -1
print(margins)
print(margins[1])

(10, 1)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
45
[[ 0]
 [-1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]]
[-1]


In [5]:
metrix = np.arange(20).reshape((4,5))
print(metrix)
print(metrix[range(4),range(4)])
print(np.sum(metrix, axis=0))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[ 0  6 12 18]
[30 34 38 42 46]


In [2]:
import matplotlib.pyplot as plt
# 创建自定义图像
fig=plt.figure(figsize=(4,3),facecolor='blue')
plt.show()

<Figure size 400x300 with 0 Axes>

In [ ]:
metrix